create or replace function public.apply_api_table_grants(target_table regclass)
returns void
language plpgsql
as $$
begin
  execute format('grant select on table %s to anon', target_table);
  execute format(
    'grant select, insert, update, delete on table %s to authenticated',
    target_table
  );
  execute format(
    'grant select, insert, update, delete on table %s to service_role',
    target_table
  );
end;
$$;

create or replace function public.apply_authenticated_sequence_grants(
  target_sequence regclass
)
returns void
language plpgsql
as $$
begin
  execute format(
    'grant usage, select on sequence %s to authenticated',
    target_sequence
  );
  execute format(
    'grant usage, select on sequence %s to service_role',
    target_sequence
  );
end;
$$;

comment on function public.apply_api_table_grants(regclass)
is 'Reusable migration helper for Supabase API table grants. Call immediately after create table, then enable RLS and add owner-scoped policies.';

comment on function public.apply_authenticated_sequence_grants(regclass)
is 'Reusable migration helper for autogenerated ID sequences tied to public tables.';

select public.apply_api_table_grants('public.module_mastery_scores'::regclass);
select public.apply_api_table_grants('public.user_progress_state'::regclass);

alter table public.module_mastery_scores enable row level security;
alter table public.user_progress_state enable row level security;

drop policy if exists "Users can read their own module mastery scores"
  on public.module_mastery_scores;
create policy "Users can read their own module mastery scores"
  on public.module_mastery_scores
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own module mastery scores"
  on public.module_mastery_scores;
create policy "Users can insert their own module mastery scores"
  on public.module_mastery_scores
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own module mastery scores"
  on public.module_mastery_scores;
create policy "Users can update their own module mastery scores"
  on public.module_mastery_scores
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own module mastery scores"
  on public.module_mastery_scores;
create policy "Users can delete their own module mastery scores"
  on public.module_mastery_scores
  for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read their own progress state"
  on public.user_progress_state;
create policy "Users can read their own progress state"
  on public.user_progress_state
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own progress state"
  on public.user_progress_state;
create policy "Users can insert their own progress state"
  on public.user_progress_state
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own progress state"
  on public.user_progress_state;
create policy "Users can update their own progress state"
  on public.user_progress_state
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own progress state"
  on public.user_progress_state;
create policy "Users can delete their own progress state"
  on public.user_progress_state
  for delete
  using (auth.uid() = user_id);
